version: '1.0.{build}'

environment:
  matrix:
    - RUBY_VERSION: 23
    - RUBY_VERSION: 23-x64


install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - bundle install

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake

notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  channel: '@vbober'
  template: cucumber-ruby/bv-contribution
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
